server:
  port: 9897

ez:
  application:
    url: https://www.tiw.cn/s/,https://www.tiw.cn
    retry-next-topic-count: 4
    topic-allow-pass-price: 0.85
    answer-allow-pass-price: 0.85


elasticsearch:
  schema: http
  address: 127.0.0.1:9200
  connectTimeout: 5000
  socketTimeout: 5000
  connectionRequestTimeout: 5000
  maxConnectNum: 100
  maxConnectPerRoute: 100